services:
  db:
  # Configuration
    image: mysql:latest
    container_name: containerSprint7
    #build: ./backend
    restart: always
    environment:
      MYSQL_DATABASE: 'dbsprint7'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'usersprint7'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    #expose:
      # Opens port 3306 on the container
      #- '3306'
      # Where our data will be persisted
    volumes:
      - db_data:/var/lib/mysql
# Names our volume
  app:
    build: .
    container_name: containerapp
    environment:
      DATABASE_URL: mysql://usersprint7:1234@db:3306/dbsprint7
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:

