# Utilitza una imatge de node com a base
FROM node:latest

# Instal·la el client de MySQL
RUN apt-get update && apt-get install -y default-mysql-client

# Estableix el directori de treball a /app
WORKDIR /app

# Copia el fitxer package.json i package-lock.json al directori de treball
COPY package*.json ./

# Instal·la les dependències
RUN npm install

# Instal·la Prisma CLI globalment
RUN npm install -g prisma

# Copia tot el codi de l'aplicació al directori de treball
COPY . .

# Genera Prisma Client
RUN npx prisma generate

# Exposa el port 3000 perquè l'aplicació pugui ser accessible a través d'aquest port
EXPOSE 3000

# Comanda per iniciar l'aplicació quan s'executi el contenidor
CMD ["npm", "run", "dev"]