services:
  XatSprint7:
  # Configuration
    image: mysql:latest
    build: ./backend
    restart: always
    environment:
      MYSQL_DATABASE: 'dbsprint7'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'usersprint7'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - dbsprint7:/var/lib/mysql
# Names our volume
volumes:
  XatSprint7: